# routers/payments.py
import os
import stripe
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, EmailStr

router = APIRouter(prefix="/api/payments", tags=["payments"])
stripe.api_key = os.environ.get("STRIPE_API_KEY")
FRONTEND_URL = os.environ.get("FRONTEND_URL", "https://faleh.franchisemiddleeast.com")


class CreateCheckoutRequest(BaseModel):
    customer_email: EmailStr
    report_url: str          # Cloudinary secure_url, already generated by n8n
    public_id: str | None = None


class CreateCheckoutResponse(BaseModel):
    checkout_url: str
    session_id: str


@router.post("/create-checkout-session", response_model=CreateCheckoutResponse)
def create_checkout_session(payload: CreateCheckoutRequest):
    try:
        session = stripe.checkout.Session.create(
            mode="payment",
            payment_method_types=["card"],
            customer_email=payload.customer_email,
            line_items=[
                {"price": "price_1Tn6rm4oljPjf5VDnSKAde7c", "quantity": 1}
            ],
            # Generates a real Stripe Invoice for this payment — gives you
            # hosted_invoice_url + invoice_pdf after payment.
            invoice_creation={"enabled": True},
            metadata={
                "report_url": payload.report_url,
                "public_id": payload.public_id or "",
            },
            success_url=f"{FRONTEND_URL}/confirm?session_id={{CHECKOUT_SESSION_ID}}",
            cancel_url=f"{FRONTEND_URL}/checkout-cancelled",
        )
        return CreateCheckoutResponse(checkout_url=session.url, session_id=session.id)
    except stripe.error.StripeError as e:
        print(e)
        raise HTTPException(status_code=400, detail=str(e))


@router.get("/session/{session_id}")
def get_checkout_session(session_id: str):
    try:
        # expand=["invoice"] gets the full invoice object (not just its ID)
        # in one call, so we can return hosted_invoice_url/invoice_pdf directly.
        session = stripe.checkout.Session.retrieve(session_id, expand=["invoice"])
    except stripe.error.InvalidRequestError:
        raise HTTPException(status_code=404, detail="Session not found")

    invoice = session.invoice  # expanded object, or None
    return {
        "paid": session.payment_status == "paid",
        "email": session.customer_details.email if session.customer_details else None,
        "report_url": session.metadata.get("report_url"),
        "invoice_url": invoice.hosted_invoice_url if invoice else None,
        "invoice_pdf": invoice.invoice_pdf if invoice else None,
    }